CREATE DATABASE IF NOT EXISTS fieldwire;

CREATE TABLE IF NOT EXISTS project (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name CHAR(50), NOT NULL,

);
-- CREATE TABLE IF NOT EXISTS floorplan;
-- CREATE TABLE IF NOT EXISTS project_floorplan;